version: '3.7'
services:
  clean-cef:
    image: translatednet/clean-cef:latest
    networks:
      traefik:
        aliases:
          - cef-datamarketplace-tmcleaning.translated.com
    logging:
      driver: json-file
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:           
            - node.role == manager
            - node.labels.zone == dc
      labels:
        - traefik.enable=true
        - traefik.http.routers.clean-cef.service=clean-cef
        - traefik.http.routers.clean-cef.rule=Host(`cef-datamarketplace-tmcleaning.translated.com`)
        - traefik.http.routers.clean-cef.entryPoints=web
        - traefik.http.services.clean-cef.loadBalancer.server.port=8081
        - traefik.http.services.clean-cef.loadBalancer.passHostHeader=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network = traefik
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 60s
      resources:
        limits:
          cpus: '2'
          memory: 2G   
networks:
  traefik:
    external: true
    
